services:
  main:
    build:
      context: .
      dockerfile: Containerfile
      args:
        USER_ID: ${USER_ID:-1000}
        USER_NAME: ${USER_NAME:-default}
    volumes:
      # Project
      - .:/usr/src/app
      # Kubernetes, Helm and Helmfile
      - ~/.cache:/home/${USER_NAME:-default}/.cache
      - ~/.config:/home/${USER_NAME:-default}/.config
      - ~/.kube:/home/${USER_NAME:-default}/.kube
    env_file: .env
    network_mode: host
    tty: true
