root:
  workloads:
    default:
      replicas: 2
      revisionHistoryLimit: 10

      strategy:
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1

      containers:
        default:
          image: ghcr.io/hidracloud/hidra:v3.4.4
          command:
            - hidra
          args:
            - exporter
            - /etc/hidra/hidra.yml
          envFrom:
            configMaps:
              - env
            secrets:
              - env
          volumeMounts:
            - name: config
              mountPath: /etc/hidra
              readOnly: true
            - name: samples
              mountPath: /etc/hidra/samples
              readOnly: true
          ports:
            - name: http
              containerPort: 19090
          probes:
            startup:
              httpGet:
                path: /_health
                port: http
              initialDelaySeconds: 5
            readiness:
              httpGet:
                path: /_health
                port: http
              initialDelaySeconds: 5
            liveness:
              httpGet:
                path: /_health
                port: http
              initialDelaySeconds: 5

      volumes:
        - name: config
          configMap:
            name: config
        - name: samples
          configMap:
            name: samples

      disruptionBudget:
        maxUnavailable: 1

      networkPolicy: {}

      service:
        annotations:
          service.kubernetes.io/topology-mode: Auto
          prometheus.io/scrape: "true"
          prometheus.io/port: "19090"
        type: ClusterIP
        ports:
          - name: http
            port: 80
            targetPort: http

  configMaps:
    env: {}

    config:
      hidra.yml: |
        log_level: info
        http_server:
          listen_address: :19090
        samples_path: /etc/hidra/samples
        scheduler:
          refresh_samples_interval: 60s
          enqueue_samples_interval: 5s
          gc_interval: 5m
        basic_auth:
          enabled: false
        worker:
          parallel_jobs: 4
          max_queue_size: 100
          sleep_between_jobs: 1s
          disable_bg_tasks: false
        report:
          enabled: false
        usage:
          enabled: true

    samples: {}

  # Don't add secrets here in version-controlled files, as they would be exposed!
  # This object should only contain empty keys for documentation purposes.
  secrets:
    env: {}
