{{- range $binding := .Values.roleBindings }}
{{- if not (hasKey $binding "namespaces") }}
{{- $name := default $binding.ref.name $binding.name }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: "{{ include "nebux-generic.resourceName" (dict "name" $name "release" $.Release.Name) }}"

  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"

roleRef:
  kind: "{{ $binding.ref.kind }}"
  apiGroup: rbac.authorization.k8s.io
  name: "{{ include "nebux-generic.resourceName" (dict "name" $binding.ref.name "release" $.Release.Name) }}"

subjects:
  {{- range $subject := $binding.subjects }}
  - kind: "{{ $subject.kind }}"
    {{- if ne $subject.kind "ServiceAccount" }}
    apiGroup: rbac.authorization.k8s.io
    {{- end }}
    name: "{{ include "nebux-generic.resourceName" (dict "name" $subject.name "release" $.Release.Name) }}"

    {{- if hasKey $subject "namespace" }}
    namespace: "{{ include "nebux-generic.namespace" (dict "namespace" $subject.namespace "release" $.Release.Namespace) }}"
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
