{{- range $configKey, $config := .Values.configMaps }}
---
kind: ConfigMap
apiVersion: v1

metadata:
  name: "{{ include "nebux-generic.name" (dict "root" $ "kind" "configMaps" "key" $configKey) }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"

data: {{ toYaml $config | nindent 2 }}
{{- end }}
