{{- range $secretKey, $auths := .Values.imagePullSecrets }}
---
kind: Secret
apiVersion: v1

metadata:
  name: "{{ include "nebux-generic.name" (dict "root" $ "key" $secretKey) }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"

type: kubernetes.io/dockerconfigjson

stringData:
  .dockerconfigjson: {{ include "nebux-generic.dockerConfig" $auths | quote }}
{{- end }}
