{{- range $pvcKey, $pvc := .Values.persistentVolumeClaims }}
---
kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: "{{ include "nebux-generic.name" (dict "root" $ "kind" "persistentVolumeClaims" "key" $pvcKey) }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"


spec: {{ toYaml $pvc | nindent 2 }}
{{- end }}
