{{- range $role := .Values.roles }}
{{- if hasKey $role "namespaces" }}
{{- range $namespace := $role.namespaces }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: "{{ include "nebux-generic.resourceName" (dict "name" $role.name "release" $.Release.Name) }}"
  namespace: "{{ include "nebux-generic.namespace" (dict "namespace" $namespace "release" $.Release.Namespace) }}"

  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"

rules: {{ toYaml $role.rules | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
