{{- range $binding := .Values.roleBindings }}
{{- if hasKey $binding "namespaces" }}
{{- $name := default $binding.ref.name $binding.name }}
{{- range $namespace := $binding.namespaces }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: "{{ include "nebux-generic.reference" (dict "root" $ "name" $name) }}"
  namespace: "{{ include "nebux-generic.namespace" (dict "root" $ "namespace" $namespace) }}"

  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"

roleRef:
  kind: "{{ $binding.ref.kind }}"
  apiGroup: rbac.authorization.k8s.io
  name: "{{ include "nebux-generic.reference" (dict "root" $ "name" $binding.ref.name) }}"

subjects:
  {{- range $subject := $binding.subjects }}
  - kind: "{{ $subject.kind }}"
    {{- if ne $subject.kind "ServiceAccount" }}
    apiGroup: rbac.authorization.k8s.io
    {{- end }}
    name: "{{ include "nebux-generic.reference" (dict "root" $ "name" $subject.name) }}"

    {{- if hasKey $subject "namespace" }}
    namespace: "{{ include "nebux-generic.namespace" (dict "root" $ "namespace" $subject.namespace) }}"
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
