{{- range $role := .Values.roles }}
{{- if hasKey $role "namespaces" }}
{{- range $namespace := $role.namespaces }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: "{{ include "nebux-generic.reference" (dict "root" $ "name" $role.name) }}"
  namespace: "{{ include "nebux-generic.namespace" (dict "root" $ "namespace" $namespace) }}"

  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"

rules: {{ toYaml $role.rules | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
