{{- range $account := .Values.serviceAccounts }}
---
kind: ServiceAccount
apiVersion: v1

metadata:
  name: "{{ include "nebux-generic.reference" (dict "root" $ "name" $account.name) }}"

  {{- $namespace := default $.Release.Namespace $account.namespace }}
  namespace: "{{ include "nebux-generic.namespace" (dict "root" $ "namespace" $namespace) }}"
  
  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
{{- end }}
