{{- range $account := .Values.serviceAccounts }}
---
kind: ServiceAccount
apiVersion: v1

metadata:
  name: "{{ include "nebux-generic.resourceName" (dict "name" $account.name "release" $.Release.Name) }}"

  {{- $namespace := default $.Release.Namespace $account.namespace }}
  namespace: "{{ include "nebux-generic.namespace" (dict "namespace" $namespace "release" $.Release.Namespace) }}"
  
  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
{{- end }}
