{{- range $udpRoute := .Values.udpRoutes }}
{{- $hasUdpRoutes := gt (len $.Values.udpRoutes) 1 }}
---
kind: UDPRoute
apiVersion: gateway.networking.k8s.io/v1

metadata:
  name: "{{ $.Release.Name }}{{ if $hasUdpRoutes }}-{{ $udpRoute.name }}{{ end }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"

spec:
  {{- if hasKey $udpRoute "parentRefs" }}
  parentRefs: {{ toYaml $udpRoute.parentRefs | nindent 4 }}
  {{- end }}

  rules:
    {{- range $rule := $udpRoute.rules }}
    - {{- if hasKey $rule "name" }}
      name: {{ toYaml $rule.name | nindent 8 }}
      {{- end }}

      {{- if hasKey $rule "backendRefs" }}
      backendRefs:
        {{- range $backendRef := $rule.backendRefs }}
        - {{- if hasKey $backendRef "name" }}
          name: "{{ include "nebux-generic.resourceName" (dict "name" $backendRef.name "release" $.Release.Name) }}"
          {{- else }}
          name: "{{ $.Release.Name }}"
          {{- end }}

          {{- if hasKey $backendRef "port" }}
          port: {{ $backendRef.port }}
          {{- end }}

          {{- if hasKey $backendRef "group" }}
          group: {{ toYaml $backendRef.group | nindent 12 }}
          {{- end }}

          {{- if hasKey $backendRef "kind" }}
          kind: {{ toYaml $backendRef.kind | nindent 12 }}
          {{- end }}

          {{- if hasKey $backendRef "namespace" }}
          namespace: {{ toYaml $backendRef.namespace | nindent 12 }}
          {{- end }}

          {{- if hasKey $backendRef "weight" }}
          weight: {{ toYaml $backendRef.weight | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
