{{- range $workloadKey, $workload := .Values.workloads }}
{{- $workloadType := default "Deployment" $workload.type }}
{{- $isStatefulSet := eq $workloadType "StatefulSet" }}
{{- $hasComponents := gt (len $.Values.workloads) 1 }}
{{- $isBlueGreen := and (hasKey (default dict $workload.strategy) "blueGreenUpdate") (not $isStatefulSet) }}
{{- range $slot := ($isBlueGreen | ternary (tuple "blue" "green") (tuple "")) }}
---
kind: "{{ $workloadType }}"
apiVersion: apps/v1

metadata:
  name: "{{ $.Release.Name }}{{ if $hasComponents }}-{{ $workloadKey }}{{ end }}{{ if $isBlueGreen }}-{{ $slot }}{{ end }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    {{- if $hasComponents }}
    app.kubernetes.io/component: "{{ $workloadKey }}"
    {{- end }}
    {{- if $isBlueGreen }}
    app.kubernetes.io/slot: "{{ $slot }}"
    {{- end }}

spec:
  {{- if $isBlueGreen }}
  {{- $strategy := $workload.strategy.blueGreenUpdate }}
  {{- $isTarget := eq $strategy.targetSlot $slot }}
  {{- $isCurrent := eq $strategy.currentSlot $slot }}
  {{- $isOngoing := ne $strategy.currentSlot $strategy.targetSlot }}
  {{- if and $workload.autoscaling $isTarget }}
  {{- else if $isCurrent }}
  replicas: {{ $strategy.currentReplicas }}
  {{- else if $isOngoing }}
  replicas: {{ $strategy.pastReplicas }}
  {{- else }}
  replicas: 0
  {{- end }}
  {{- else if $workload.replicas }}
  replicas: {{ $workload.replicas }}
  {{- end }}

  revisionHistoryLimit: {{ $workload.revisionHistoryLimit }}

  {{- if and (not $isBlueGreen) (hasKey $workload "strategy") }}
  {{ $isStatefulSet | ternary "updateStrategy" "strategy" }}: {{ toYaml $workload.strategy | nindent 4 }}
  {{- end }}

  {{- if hasKey $workload "minReadySeconds" }}
  minReadySeconds: {{ $workload.minReadySeconds }}
  {{- end }}

  {{- if $isStatefulSet }}
  {{- if hasKey $workload "ordinals" }}
  ordinals: {{ toYaml $workload.ordinals | nindent 4 }}
  {{- end }}

  {{- if hasKey $workload "serviceName" }}
  serviceName: "{{ include "nebux-generic.resourceName" (dict "name" $workload.serviceName "release" $.Release.Name) }}"
  {{- end }}

  {{- if hasKey $workload "podManagementPolicy" }}
  podManagementPolicy: "{{ $workload.podManagementPolicy }}"
  {{- end }}

  {{- if hasKey $workload "persistentVolumeClaimRetentionPolicy" }}
  persistentVolumeClaimRetentionPolicy: {{ toYaml $workload.persistentVolumeClaimRetentionPolicy | nindent 4 }}
  {{- end }}

  {{- if hasKey $workload "volumeClaimTemplates" }}
  volumeClaimTemplates:
    {{- range $volume := $workload.volumeClaimTemplates }}
    - metadata:
        name: "{{ include "nebux-generic.resourceName" (dict "name" $volume.metadata.name "release" $.Release.Name) }}"
      spec: {{ toYaml $volume.spec | nindent 8 }}
    {{- end }}
  {{- end }}
  {{- end }}

  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ $.Release.Name }}"
      {{- if $hasComponents }}
      app.kubernetes.io/component: "{{ $workloadKey }}"
      {{- end }}
      {{- if $isBlueGreen }}
      app.kubernetes.io/slot: "{{ $slot }}"
      {{- end }}

  template:
    metadata:
      labels:
        app.kubernetes.io/instance: "{{ $.Release.Name }}"
        {{- if $hasComponents }}
        app.kubernetes.io/component: "{{ $workloadKey }}"
        {{- end }}
        {{- if $isBlueGreen }}
        app.kubernetes.io/slot: "{{ $slot }}"
        {{- end }}
      annotations:
        configmaps-hash: "{{ $.Values.configMaps | toYaml | sha256sum | trunc 8 }}"
        secrets-hash: "{{ $.Values.secrets | toYaml | sha256sum | trunc 8 }}"

    spec:
      {{- if hasKey $workload "tolerations" }}
      tolerations: {{ toYaml $workload.tolerations | nindent 8 }}
      {{- end }}

      {{- if hasKey $workload "nodeSelector" }}
      nodeSelector: {{ toYaml $workload.nodeSelector | nindent 8 }}
      {{- end }}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - "{{ $.Release.Name }}"
                    {{- if $hasComponents }}
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - "{{ $workloadKey }}"
                    {{- end }}
                    {{- if $isBlueGreen }}
                    - key: app.kubernetes.io/slot
                      operator: In
                      values:
                        - "{{ $slot }}"
                    {{- end }}

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: "{{ $.Release.Name }}"
              {{- if $hasComponents }}
              app.kubernetes.io/component: "{{ $workloadKey }}"
              {{- end }}
              {{- if $isBlueGreen }}
              app.kubernetes.io/slot: "{{ $slot }}"
              {{- end }}

      {{- if hasKey $workload "restartPolicy" }}
      restartPolicy: {{ toYaml $workload.restartPolicy | nindent 8 }}
      {{- end }}

      {{- if hasKey $workload "enableServiceLinks" }}
      enableServiceLinks: {{ toYaml $workload.enableServiceLinks | nindent 8 }}
      {{- end }}

      {{- if hasKey $workload "imagePullSecrets" }}
      imagePullSecrets:
        {{- range $pullSecret := $workload.imagePullSecrets }}
        - name: "{{ include "nebux-generic.resourceName" (dict "name" $pullSecret.name "release" $.Release.Name) }}"
        {{- end }}
      {{- end }}

      {{- if hasKey $workload "volumes" }}
      volumes:
        {{- range $volume := $workload.volumes }}
        - name: "{{ $volume.name }}"
          {{- if hasKey $volume "configMap" }}
          configMap:
            name: "{{ include "nebux-generic.configRef" (dict "name" $volume.configMap.name "release" $.Release.Name "count" (len $.Values.configMaps)) }}"
          {{- end }}
          {{- if hasKey $volume "secret" }}
          secret:
            secretName: "{{ include "nebux-generic.configRef" (dict "name" $volume.secret.secretName "release" $.Release.Name "count" (len $.Values.secrets)) }}"
          {{- end }}
          {{- if hasKey $volume "hostPath" }}
          hostPath: {{ toYaml $volume.hostPath | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}

      {{- if hasKey $workload "securityContext" }}
      securityContext: {{ toYaml $workload.securityContext | nindent 8 }}
      {{- end }}

      {{- if hasKey $workload "serviceAccountName" }}
      serviceAccountName: "{{ include "nebux-generic.resourceName" (dict "name" $workload.serviceAccountName "release" $.Release.Name) }}"
      {{- end }}

      {{- range $containerType := tuple "initContainers" "containers" }}
      {{- if hasKey $workload $containerType }}
      {{ $containerType }}:
        {{- range $containerName, $container := index $workload $containerType }}
        - name: "{{ $containerName }}"

          {{- $hasSlottedImage := kindIs "map" $container.image }}
          {{- if not $hasSlottedImage }}
          image: "{{ $container.image }}"
          {{- else }}
          image: "{{ index $container "image" $slot }}"
          {{- end }}

          {{- if hasKey $container "imagePullPolicy" }}
          imagePullPolicy: {{ toYaml $container.imagePullPolicy | nindent 12 }}
          {{- end }}

          {{- if hasKey $container "command" }}
          command: {{ toYaml $container.command | nindent 12 }}
          {{- end }}

          {{- if hasKey $container "args" }}
          args: {{ toYaml $container.args | nindent 12 }}
          {{- end }}

          {{- if hasKey $container "restartPolicy" }}
          restartPolicy: {{ toYaml $container.restartPolicy | nindent 12 }}
          {{- end }}

          {{- if hasKey $container "lifecycle" }}
          lifecycle: {{ toYaml $container.lifecycle | nindent 12 }}
          {{- end }}

          {{- if hasKey $container "envFrom" }}
          envFrom:
            {{- range $configMap := $container.envFrom.configMaps }}
            - configMapRef:
                name: "{{ include "nebux-generic.configRef" (dict "name" $configMap "release" $.Release.Name "count" (len $.Values.configMaps)) }}"
            {{- end }}
            {{- range $secret := $container.envFrom.secrets }}
            - secretRef:
                name: "{{ include "nebux-generic.configRef" (dict "name" $secret "release" $.Release.Name "count" (len $.Values.secrets)) }}"
            {{- end }}
          {{- end }}

          {{- if hasKey $container "env" }}
          {{- $envs := list }}
          {{- range $env := $container.env }}
          {{- if hasKey (default dict $env.valueFrom) "secretKeyRef" }}
          {{- $name := include "nebux-generic.configRef" (dict "name" $env.valueFrom.secretKeyRef.name "release" $.Release.Name "count" (len $.Values.secrets)) }}
          {{- $env = mergeOverwrite (deepCopy $env) (dict "valueFrom" (dict "secretKeyRef" (dict "name" $name))) }}
          {{- else if hasKey (default dict $env.valueFrom) "configMapKeyRef" }}
          {{- $name := include "nebux-generic.configRef" (dict "name" $env.valueFrom.configMapKeyRef.name "release" $.Release.Name "count" (len $.Values.configMaps)) }}
          {{- $env = mergeOverwrite (deepCopy $env) (dict "valueFrom" (dict "configMapKeyRef" (dict "name" $name))) }}
          {{- end }}
          {{- $envs = append $envs $env }}
          {{- end }}
          env: {{ toYaml $envs | nindent 12 }}
          {{- end }}

          {{- if hasKey $container "volumeMounts" }}
          volumeMounts: {{ toYaml $container.volumeMounts | nindent 12 }}
          {{- end }}

          {{- if hasKey $container "resources" }}
          resources: {{ toYaml $container.resources | nindent 12 }}
          {{- end }}

          {{- if hasKey $container "ports" }}
          ports: {{ toYaml $container.ports | nindent 12 }}
          {{- end }}

          {{- range $probeType, $probeConfig := $container.probes }}
          {{ $probeType }}Probe: {{ toYaml $probeConfig | nindent 12 }}
          {{- end }}

          {{- if hasKey $container "securityContext" }}
          securityContext: {{ toYaml $container.securityContext | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
