{{- range $configKey, $config := .Values.configMaps }}
---
kind: ConfigMap
apiVersion: v1

metadata:
  name: "{{ $.Release.Name }}{{ if gt (len $.Values.configMaps) 1 }}-{{ $configKey }}{{ end }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"

data: {{ toYaml $config | nindent 2 }}
{{- end }}
