{{- range $workloadKey, $workload := .Values.workloads }}
{{- if $workload.autoscaling }}
{{- $hasComponents := gt (len $.Values.workloads) 1 }}
{{- $isBlueGreen := hasKey $workload.strategy "blueGreenUpdate" }}
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1

metadata:
  name: "{{ $.Release.Name }}{{ if $hasComponents }}-{{ $workloadKey }}{{ end }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    {{- if $hasComponents }}
    app.kubernetes.io/component: "{{ $workloadKey }}"
    {{- end }}

spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: "{{ $.Release.Name }}{{ if $hasComponents }}-{{ $workloadKey }}{{ end }}{{ if $isBlueGreen }}-{{ $workload.strategy.blueGreenUpdate.targetSlot }}{{ end }}"

  targetCPUUtilizationPercentage: {{ $workload.autoscaling.targetCPUUtilizationPercentage }}
  
  minReplicas: {{ $workload.autoscaling.replicas.min }}
  maxReplicas: {{ $workload.autoscaling.replicas.max }}
{{- end }}
{{- end }}
