{{- range $workloadKey, $workload := .Values.workloads }}
{{- if $workload.disruptionBudget }}
{{- $hasComponents := gt (len $.Values.workloads) 1 }}
---
kind: PodDisruptionBudget
apiVersion: policy/v1

metadata:
  name: "{{ $.Release.Name }}{{ if $hasComponents }}-{{ $workloadKey }}{{ end }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    {{- if $hasComponents }}
    app.kubernetes.io/component: "{{ $workloadKey }}"
    {{- end }}

spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ $.Release.Name }}"
      {{- if $hasComponents }}
      app.kubernetes.io/component: "{{ $workloadKey }}"
      {{- end }}

  {{- range $key, $value := $workload.disruptionBudget }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
{{- end }}
