{{- range $secretKey, $secret := .Values.secrets }}
---
kind: Secret
apiVersion: v1

metadata:
  name: "{{ $.Release.Name }}{{ if gt (len $.Values.secrets) 1 }}-{{ $secretKey }}{{ end }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"

type: Opaque

stringData: {{ toYaml $secret | nindent 2 }}
{{- end }}
